//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderType
    {
        [Display(Name="Order Code")]
        public string OrderCode { get; set; }
        [Display(Name ="Name")]
        public string OrderName { get; set; }
        [Display(Name ="Specimen")]
        public string SpecimenType { get; set; }

        public virtual ICollection<PatientOrder> PatientOrder{ get; set; }
    }
}
