//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.ModelBinding;

    public partial class PatientOrder
    {
        [Display(Name ="Patient Order ID")]
        public int PatientOrderId { get; set; }

        [Required]
        [Display(Name ="Creation Date")]
        [DataType(DataType.Date)]
        public DateTime CreationDate { get; set; }

        [Key]
        [ForeignKey("Patient")]
        [Required]
        [Display(Name ="Patient ID")]
        public Nullable<int> PatientId { get; set; }

        [Key]
        [ForeignKey("OrderType")]
        [Required]
        [Display(Name ="Order Code")]
        public string OrderCode { get; set; }
        public string Status { get; set; }

        public virtual OrderType OrderType { get; set; }
    }
}
